version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./redis-config/redis.conf:/redis-stack.conf
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
